swagger: "2.0"
info:
  description: "CNAS Rest API"
  version: "1.0.0"
  title: "CNAS"
host: "localhost:8089"
basePath: "/cnas-management"
schemes:
  - "http"
paths:
  /patients:
    get:
      description: "Returns a list of patients"
      operationId: "getPatients"
      produces:
        - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Patient"
  /patients/{cnp}:
    get:
      summary: "Find patient by CNP"
      description: "Returns a single patient"
      operationId: "getPatientByCNP"
      produces:
        - "application/json"
      parameters:
        - name: "cnp"
          in: "path"
          description: "CNP of patient to return"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Patient"
        "400":
          description: "Invalid CNP supplied"
        "404":
          description: "Patient not found"
definitions:
  Patient:
    type: "object"
    properties:
      cnp:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      birthdate:
        type: "string"
        format: "date"
      status:
        type: "string"
        description: "assured"
        enum:
          - "somer"
          - "angajat"
          - "pensionar"
          - "neasigurat"